sudo: false  # use containers with travis
language: python
python:
  - "2.7"
install:
  - BUILD_CCTOOLS=1 ./install_dependencies.sh
  - pip install matplotlib
  - pip install .
before_script:
  - export LOBSTER_STORAGE=$PWD/test_storage/
  - export LOBSTER_SKIP_HADOOP=1
  - export LOBSTER_SKIP_SRM=1
script:
  - nosetests
  - flake8 lobster
addons:
  apt:
    packages:
      - swig
notifications:
  slack: ndlobster:KTPb95b6ZKyFZiNvsPp723HS
