sudo: false  # use containers with travis
language: python
python:
  - "2.7"
install:
  - BUILD_CCTOOLS=1 ./install_dependencies.sh
  - pip install matplotlib
  - pip install flake8
  - pip install pycurl
  - pip install mock
  - pip install .
before_script:
  - export LOBSTER_STORAGE=$PWD/test_storage/
  - export LOBSTER_SKIP_HADOOP=1
  - export LOBSTER_SKIP_SRM=1
env:
  - TESTCOMMAND="flake8 --exclude=.git,cctools-*,docs ."
  - TESTCOMMAND=nosetests
script:
  - $TESTCOMMAND
addons:
  apt:
    packages:
      - libgnutls28-dev
      - swig
notifications:
  slack: ndlobster:KTPb95b6ZKyFZiNvsPp723HS
