sudo: false  # use containers with travis
language: python
python:
  - "2.7"
install:
  - BUILD_CCTOOLS=1 ./install_dependencies.sh
  - pip install .
# before_script:
#   - uname -a
script:
  - nosetests
addons:
  apt:
    packages:
      - swig
