sudo: false  # use containers with travis
language: python
python:
  - "2.7"
install:
  - ./install_dependencies.sh
  - pip install matplotlib
  - pip install numpy
  - pip install .
# before_script:
#   - uname -a
script:
  - nosetests
